name: 'Storybook Tests'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-serve-run-storybook-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook -- --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "STORYBOOK,TEST" -c "magenta,cyan" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run test-storybook"
